### ISSUE TITLE
Redundant Save call (IMO)

### ISSUE THREAD

**Issue by kylehqcom** [josephspurrier/csrfbanana#5]
https://github.com/josephspurrier/csrfbanana/blob/master/csrfbanana.go#L112-L113

What is the purpose of this call? As far as I can see, nothing destructive has occurred to the current session so why invoke a save here? The regenerateAfterUsage/refresh which is checked on `match` only deletes the path from the StringMap, not the session so I don't think this save is required.

Can you confirm, what am I missing?
Thanks

**Comment by josephspurrier** [comment]
You are correct. I don't know why I left it in there. I removed it. Thanks. https://github.com/josephspurrier/csrfbanana/commit/285890d829d0e100b266293fab5cd72d9280f29b

**Comment by kylehqcom** [comment]
Love your work <3
